$primary = rgb({{colors.primary.default.hex_stripped}})
$primary_fixed = rgb({{colors.primary_fixed.default.hex | replace: "#", ""}})
$surface_variant = rgb({{colors.surface_variant.default.hex_stripped}})
